services:
  auth:
    build:
      context: ../../.
      dockerfile: Dockerfile
    image: ghcr.io/dirathea/pasolo:v0.2.0
    env_file:
      - .env
    environment:
      STORE_DATADIR: /secret
    ports:
      - 8080
    volumes:
      - secret:/secret

  app:
    depends_on:
      - auth
      - target
    image: caddy:2
    ports:
      - 443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile

  target:
    image: jmalloc/echo-server
    expose:
      - 8080

volumes:
  secret: